/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meteogroup_jbrotli_BrotliCompressor */

#ifndef _Included_com_meteogroup_jbrotli_BrotliCompressor
#define _Included_com_meteogroup_jbrotli_BrotliCompressor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_meteogroup_jbrotli_BrotliCompressor
 * Method:    compressBytes
 * Signature: (IIII[BII[BII)I
 */
JNIEXPORT jint JNICALL Java_com_meteogroup_jbrotli_BrotliCompressor_compressBytes
  (JNIEnv *, jclass, jint, jint, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_meteogroup_jbrotli_BrotliCompressor
 * Method:    compressByteBuffer
 * Signature: (IIIILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_com_meteogroup_jbrotli_BrotliCompressor_compressByteBuffer
  (JNIEnv *, jclass, jint, jint, jint, jint, jobject, jint, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
