/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_meteogroup_jbrotli_BrotliStreamEncoder */

#ifndef _Included_org_meteogroup_jbrotli_BrotliStreamEncoder
#define _Included_org_meteogroup_jbrotli_BrotliStreamEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_meteogroup_jbrotli_BrotliStreamEncoder
 * Method:    initJavaFieldIdCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_meteogroup_jbrotli_BrotliStreamEncoder_initJavaFieldIdCache
  (JNIEnv *, jclass);

/*
 * Class:     org_meteogroup_jbrotli_BrotliStreamEncoder
 * Method:    initNativeEncoder
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_meteogroup_jbrotli_BrotliStreamEncoder_initNativeEncoder
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_meteogroup_jbrotli_BrotliStreamEncoder
 * Method:    freeNativeResources
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_meteogroup_jbrotli_BrotliStreamEncoder_freeNativeResources
  (JNIEnv *, jobject);

/*
 * Class:     org_meteogroup_jbrotli_BrotliStreamEncoder
 * Method:    processNative
 * Signature: (Ljava/nio/ByteBuffer;II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_meteogroup_jbrotli_BrotliStreamEncoder_processNative
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     org_meteogroup_jbrotli_BrotliStreamEncoder
 * Method:    flushNative
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_meteogroup_jbrotli_BrotliStreamEncoder_flushNative
  (JNIEnv *, jobject);

/*
 * Class:     org_meteogroup_jbrotli_BrotliStreamEncoder
 * Method:    finishNative
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_meteogroup_jbrotli_BrotliStreamEncoder_finishNative
  (JNIEnv *, jobject);

/*
 * Class:     org_meteogroup_jbrotli_BrotliStreamEncoder
 * Method:    BrotliEncoderTakeOutput
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_meteogroup_jbrotli_BrotliStreamEncoder_BrotliEncoderTakeOutput
  (JNIEnv *, jobject);

/*
 * Class:     org_meteogroup_jbrotli_BrotliStreamEncoder
 * Method:    brotliEncoderIsFinished
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_meteogroup_jbrotli_BrotliStreamEncoder_brotliEncoderIsFinished
  (JNIEnv *, jobject);

/*
 * Class:     org_meteogroup_jbrotli_BrotliStreamEncoder
 * Method:    brotliEncoderHasMoreOutput
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_meteogroup_jbrotli_BrotliStreamEncoder_brotliEncoderHasMoreOutput
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
